embedding: |
  Given a cosmetic ingredients listed in the given order of content, find the ingredient list that matches the most formulation, application, and base.

reranker: |
  Given a cosmetic ingredients listed in the given order of content, find the ingredient list that matches the most formulation, application, and base.

generator:
  rag: |
    Based on the provided context, please answer the following question.
    ---
    Context: {context}
    ---
    Question: {question}
    ---
    Answer: