recommendation:
  _target_: src.managers.RecommendationManager
  embedding: ${model.embedding}
  reranker: ${model.reranker}
  index: ${database}
  score_column_name: ${score_column_name}
  rerank_top_k: ${top_k.rerank}

report:
  _target_: src.managers.ReportManager
  generator: ${model.generator}