# @package _global_
defaults:
  - database: vector_store
  - model: model
  - instruction: instruction
  - manager: manager
  - hydra: hydra

package_name: allganize-test
project_dir: ${oc.env:PROJECT_DIR}/${package_name}
connected_dir: ${oc.env:CONNECTED_DIR}/${package_name}
usage: RAG

seed: 2025

data_path: ${connected_dir}/data
documents_name: documents.csv
items_name: documents_with_chunks.csv
indices_name: rag_db.faiss
eval_file_name: rag_evaluation_result.csv
result_file_name: rag_results.csv

distance_column_name: distance
score_column_name: score

role_column_name: role
content_column_name: content

model_family: Qwen/Qwen3
model_id:
  embedding: ${model_family}-Embedding-0.6B
  reranker: ${model_family}-Reranker-0.6B
  generator: ${model_family}-0.6B

dim: 1024
num_gpus: ${oc.decode:${oc.env:DEVICES}}

gpu_memory_utilization:
  embedding: 0.25
  reranker: 0.25
  generator: 0.45

max_length: 4096
generator_max_length: 8192
max_new_tokens: 2048
do_sample: true
generation_config:
  temperature: 0.6
  top_p: 0.95
  top_k: 20

top_k:
  retrieval: 20
  rerank: 3

device_id:
  embedding: 0
  reranker: 0
  generator: 0
master_addr: 127.0.0.1
master_port:
  embedding: 29501
  reranker: 29511
  generator: 29521
nccl_socket_ifname: lo
nccl_ib_disable: 1

project_name: ${package_name}-${usage}

run_name: ${project_name}
work_dir: ${hydra:runtime.cwd}